server:
  port: 8081

spring:
  application:
    name: smart-study-planner

  datasource:
    url: jdbc:postgresql://localhost:5433/studyplanner
    username: studyplanner
    password: studyplanner
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true